# -----------------------------------------------------------------------------
# Visuals
# -----------------------------------------------------------------------------

# Panes
# set -g pane-border-status bottom
#set -g pane-border-style fg="#0F111A bg=#0F111A"
#set -g pane-active-border-style "bg=#0F111A fg=magenta"

# Titles
set -g set-titles on
# window number,program name, active(or not)
set -g set-titles-string '#H  #S #W(#I.#P) #T' 

# Status bar
set -g status-position top # bottom | top
set -g status-justify left # left | centre | absolute-centre | right
set -g status-bg '#0F111A'
set -g status-fg white

# Current windows status
#  #I - window index
#  #W - window title
#  #F - window flag
setw -g window-status-current-format '#[fg=yellow]#W#[fg=blue](#I)#[fg=green]#F '

# Windows status w
setw -g window-status-format '#W#[fg=blue](#I)#[fg=green]#F '

# Bell status
setw -g window-status-bell-style 'fg=colour255 bg=red bold'

# Status left
set -g status-left-length 85
#set -g status-left-style bg=#0F111A
set -g status-bg '#FFFFFF'
set -g status-left '#{?client_prefix,#[fg=green]█,#[fg=blue]█}'
set -ag status-left "#[fg=blue]   #[fg=green]#S "
set -ag status-left "#[fg=blue] "

# Status right
set -g status-right-length 120
#set -g status-right-style bg=#0F111A
set -g status-right ' #[fg=blue]#{pane_current_path} '
set -ag status-right '#[fg=green]  #{continuum_status} '
set -ag status-right ''
