set -g @theme-variant 'nord-light'
set -g @theme-bg '#eceff4'
set -g @theme-surface '#e5e9f0'
set -g @theme-surface-alt '#d8dee9'
set -g @theme-text '#4c566a'
set -g @theme-muted '#81a1c1'
set -g @theme-accent '#81a1c1'
set -g @theme-accent-alt '#b48ead'
set -g @theme-warning '#d08770'
set -g @theme-alert '#bf616a'
set -g @theme-info '#88c0d0'
set -g @theme-success '#a3be8c'
set -g status-style 'bg=#eceff4,fg=#4c566a'
