set -g @theme-variant 'tokyo-night-light'
set -g @theme-bg '#e1e2e7'
set -g @theme-surface '#d5d6db'
set -g @theme-surface-alt '#b4b5bb'
set -g @theme-text '#3760bf'
set -g @theme-muted '#4c505e'
set -g @theme-accent '#34548a'
set -g @theme-accent-alt '#5a4a78'
set -g @theme-warning '#8f5e15'
set -g @theme-alert '#8c4351'
set -g @theme-info '#0f4b6e'
set -g @theme-success '#33635c'
set -g status-style 'bg=#e1e2e7,fg=#3760bf'
