set -g @theme-variant 'material-dark'
set -g @theme-bg '#1e282d'
set -g @theme-surface '#35434d'
set -g @theme-surface-alt '#35434d'
set -g @theme-text '#c4c7d1'
set -g @theme-muted '#a1a1a1'
set -g @theme-accent '#80cbc4'
set -g @theme-accent-alt '#c3e88d'
set -g @theme-warning '#f7eb95'
set -g @theme-alert '#eb606b'
set -g @theme-info '#aeddff'
set -g @theme-success '#c3e88d'
set -g status-style 'bg=#1e282d,fg=#c4c7d1'
set -g @theme-ready '1'
