set -g @theme-variant 'gruvbox-light'
set -g @theme-bg '#fbf1c7'
set -g @theme-surface '#f2e5bc'
set -g @theme-surface-alt '#d5c4a1'
set -g @theme-text '#3c3836'
set -g @theme-muted '#7c6f64'
set -g @theme-accent '#458588'
set -g @theme-accent-alt '#b16286'
set -g @theme-warning '#d79921'
set -g @theme-alert '#cc241d'
set -g @theme-info '#689d6a'
set -g @theme-success '#98971a'
set -g status-style 'bg=#fbf1c7,fg=#3c3836'
