set -g @theme-variant 'gruvbox-dark'
set -g @theme-bg '#282828'
set -g @theme-surface '#3c3836'
set -g @theme-surface-alt '#504945'
set -g @theme-text '#ebdbb2'
set -g @theme-muted '#a89984'
set -g @theme-accent '#83a598'
set -g @theme-accent-alt '#d3869b'
set -g @theme-warning '#fabd2f'
set -g @theme-alert '#fb4934'
set -g @theme-info '#8ec07c'
set -g @theme-success '#b8bb26'
set -g status-style 'bg=#282828,fg=#ebdbb2'
