set -g @theme-variant 'solarized-dark'
set -g @theme-bg '#002b36'
set -g @theme-surface '#073642'
set -g @theme-surface-alt '#586e75'
set -g @theme-text '#839496'
set -g @theme-muted '#657b83'
set -g @theme-accent '#268bd2'
set -g @theme-accent-alt '#d33682'
set -g @theme-warning '#b58900'
set -g @theme-alert '#dc322f'
set -g @theme-info '#2aa198'
set -g @theme-success '#859900'
set -g status-style 'bg=#002b36,fg=#839496'
