set -g @theme-variant 'solarized-light'
set -g @theme-bg '#fdf6e3'
set -g @theme-surface '#eee8d5'
set -g @theme-surface-alt '#93a1a1'
set -g @theme-text '#586e75'
set -g @theme-muted '#839496'
set -g @theme-accent '#268bd2'
set -g @theme-accent-alt '#d33682'
set -g @theme-warning '#b58900'
set -g @theme-alert '#dc322f'
set -g @theme-info '#2aa198'
set -g @theme-success '#859900'
set -g status-style 'bg=#fdf6e3,fg=#586e75'
