set -g @theme-variant 'catppuccin-light'
set -g @theme-bg '#eff1f5'
set -g @theme-surface '#e6e9ef'
set -g @theme-surface-alt '#bcc0cc'
set -g @theme-text '#4c4f69'
set -g @theme-muted '#6c6f85'
set -g @theme-accent '#1e66f5'
set -g @theme-accent-alt '#ea76cb'
set -g @theme-warning '#df8e1d'
set -g @theme-alert '#d20f39'
set -g @theme-info '#179299'
set -g @theme-success '#40a02b'
set -g status-style 'bg=#eff1f5,fg=#4c4f69'
