set -g @theme-variant 'one-dark-pro-dark'
set -g @theme-bg '#282c34'
set -g @theme-surface '#3f4451'
set -g @theme-surface-alt '#4f5666'
set -g @theme-text '#abb2bf'
set -g @theme-muted '#4f5666'
set -g @theme-accent '#4aa5f0'
set -g @theme-accent-alt '#c162de'
set -g @theme-warning '#d18f52'
set -g @theme-alert '#e05561'
set -g @theme-info '#42b3c2'
set -g @theme-success '#8cc265'
set -g status-style 'bg=#282c34,fg=#abb2bf'
