set -g @theme-variant 'one-dark-pro-light'
set -g @theme-bg '#fafafa'
set -g @theme-surface '#f0f0f0'
set -g @theme-surface-alt '#d3d3d3'
set -g @theme-text '#383a42'
set -g @theme-muted '#696c77'
set -g @theme-accent '#4078f2'
set -g @theme-accent-alt '#a626a4'
set -g @theme-warning '#c18401'
set -g @theme-alert '#e45649'
set -g @theme-info '#0184bc'
set -g @theme-success '#50a14f'
set -g status-style 'bg=#fafafa,fg=#383a42'
